# Generated by Django 3.2.11 on 2022-01-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='desc',
        ),
    ]
